services:
  - type: web
    name: sp-crime-predictor
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.9"
      - key: MODEL_PATH
        value: "model.pkl"
      - key: ALLOWED_ORIGINS
        value: "*"